### ISSUE TITLE
Seems to be an issue with a library manifest and can't be built with Platformio

### ISSUE THREAD

**Issue by berkut0** [LiquidCGS/FastIMU#11]
I'm trying to port my source code to Platformio and encountered couple of weird things
1. First of all it can't be found in Platformio library search
2. Platformio "ignores broken library manifest"

<img src="https://github.com/LiquidCGS/FastIMU/assets/8849896/a68408f5-255e-4650-b4e3-9f23b3583478">

3. For now, I can't build my project directly using the library from github

<img src="https://github.com/LiquidCGS/FastIMU/assets/8849896/029eb766-b91e-40d9-aa46-7159938e93a9">
<details><summary>screenshots</summary>
Was used

```C
MPU6050 IMU;
```

<img src="https://github.com/LiquidCGS/FastIMU/assets/8849896/945941c7-9082-4191-a0a6-9a2ecf0e48ce">

<img src="https://github.com/LiquidCGS/FastIMU/assets/8849896/0f2c6e42-0bb4-4d76-bdda-798e85886be3">

</details>

**Comment by berkut0** [comment]
At least one error here:
![изображение](https://github.com/LiquidCGS/FastIMU/assets/8849896/b41e9ae5-50b4-4329-83d0-cc84c103d655)

**Comment by LiquidCGS** [comment]
I don't usually use platformio so I didn't catch this earlier oops
I'll take a closer look at this later today or tomorrow

**Comment by LiquidCGS** [comment]
I forgot to make a branch for this fix, it was just that line breaking the manifest. looks like it works now, you'll get some warnings due to me leaving an unfinished IMU type in as it's a WIP but it'll compile just fine
