### ISSUE TITLE
The magnetometer issue in F_MPU6500.cpp

### ISSUE THREAD

**Issue by rafiqrushdan** [LiquidCGS/FastIMU#14]
### The magnetometer for my unit cannot use the the set pass mode from the code. Hence I suggest we used this code

	writeByte(IMUAddress, MPU6500_INT_PIN_CFG, 0x02);	//enable Magnetometer bypass
	writeByte(IMUAddress, MPU6500_INT_ENABLE, 0x01);    // Enable data ready (bit 0) interrupt

> **Before this the code use 0x22 to enable Magnetometer to bypass.

**Comment by LiquidCGS** [comment]
Can you expand on your issue? what do you mean by "The magnetometer for my unit cannot use the the set pass mode from the code."
if you have a magnetometer just plug it directly to the i2c bus, in paralell with the IMU.
