### ISSUE TITLE
Does this work with BMX160?

### ISSUE THREAD

**Issue by SujithChristopher** [LiquidCGS/FastIMU#2]
Does this library work with BMX160? and give our calibrated Quaternion output?

Because the sensor is not mentioned in the comments. 

Thanks.

**Comment by LiquidCGS** [comment]
You might get that sensor to work as a BMI160, however if you do that you won't be able to use the magnetometer on it.

**Comment by SujithChristopher** [comment]
Okay, thank you for the reply, 

any plans on supporting, the full sensor in the future?

**Comment by SujithChristopher** [comment]
Secondly, in the comments its mentioned.

Move IMU in figure 8 pattern until done!

Do you have any links/documentation what does this figure 8 pattern mean?

This will be helpful, thanks again.

**Comment by LiquidCGS** [comment]
I'll add support for it if I can get my hands on one of them. During calibration the sketch will ask you to move the IMU in a figure 8 pattern to calibrate the magnetometer, it quite literally means, to pick up the IMU and move it in the air, drawing an "8" with it while rotating it to calculate the average magnetometer soft iron corrections.

**Comment by SujithChristopher** [comment]
Thanks
