### ISSUE TITLE
MPU9250 crashes.. Here's the fix :)

### ISSUE THREAD

**Issue by MarcGroef** [LiquidCGS/FastIMU#3]
Hi,

During testing, I found that my esp32 was crashing when using the MPU9250 from your library.
I found the issue to be that in F_MPU9250.cpp, the function int MPU9250::initMagnetometer() doesn't return an int.

Cheers!

**Comment by LiquidCGS** [comment]
Oh wow I didn't even notice that, I'll update that soonish
