### ISSUE TITLE
Support non-default I2C bus

### ISSUE THREAD

**Issue by JamesWhitlock** [LiquidCGS/FastIMU#30]
It would be useful if a TwoWire instance could be optionally passed in to the constructor to allow use of non-default I2C masters.

Let me know if you'd welcome a PR.

**Comment by LiquidCGS** [comment]
Hey! That's actually been a thing that's been on the TODO list for a bit, I've been a bit busy these past few months so I haven't worked much on the library, if you're up for doing it then go ahead and submit a PR with the changes!
