### ISSUE TITLE
Use multiple I2C channels simultaneously

### ISSUE THREAD

**Issue by Benoit-LdL** [LiquidCGS/FastIMU#36]
Hi,
For my project I use 3 MPU6050 which can change between 2 adresses. To use the third one, I want to use the second I2C channel on my ESP32 but I don't know if this library supports that. Can you tell me?

kind regards,
Benoit L

**Comment by JX5S** [comment]
Hi,
It does support it now, using non-default I2C ports. So in your case, try something like this:

MPU6050 IMU1(Wire);    // later init with 1st address
MPU6050 IMU2(Wire);    // later init with 2nd address
MPU6050 IMU3(Wire1);  // later init with 1st address

**Comment by Benoit-LdL** [comment]
Great work and many thanks for the quick reply and update!
