### ISSUE TITLE
Add qmi8658 imu?

### ISSUE THREAD

**Issue by huangjun198604** [LiquidCGS/FastIMU#7]
Qmi8658 is low price and high performance 6dof imu.

**Comment by LiquidCGS** [comment]
First time I hear about this IMU, I'll order a few and add support for it once it gets here.
Cheers

**Comment by LazaroFilm** [comment]
This module is on [this new MCU](https://www.waveshare.com/wiki/RP2040-Touch-LCD-1.28) which also has a circular touchscreen, LiPo module, and a rp2040 right on the board. This would be a great module to set things up on wearable devices.

**Comment by LiquidCGS** [comment]
Very late but support for this IMU has been added.
